global using System;
global using System.Linq;
global using System.Text;
global using System.Diagnostics;global using System.Threading.Tasks;
global using Microsoft.Maui;
global using Microsoft.Maui.Hosting;
global using Microsoft.Maui.Graphics;
global using Microsoft.Maui.Controls;
global using Microsoft.Maui.Controls.Hosting;
global using Microsoft.Extensions.DependencyInjection;
